# setup.ps1 - cr-tools source build setup (install deps + DSH + profile)
# Usage: powershell -ExecutionPolicy Bypass -File scripts/setup.ps1
# NOTE: ASCII-only file (PowerShell 5.1 reads BOM-less files as GBK; keep English).
# Steps: check node/python -> npm install DSH -> venv + pip install -> config.yaml -> profile

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot

function Say([string]$m) { Write-Host "[setup] $m" -ForegroundColor Cyan }

# -- 1) prerequisites --
Say "checking Node.js..."
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) { throw "Node.js >= 18 not found. Install from https://nodejs.org then retry." }
$nv = (& node -v).Trim()
Say "node: $nv"

$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) { throw "Python 3.11 not found. Install from https://www.python.org then retry." }
$pv = (& python --version 2>&1).Trim()
Say "python: $pv"

# -- 2) DSH platform (local node_modules; no global install needed) --
$pkg = Join-Path $Root 'package.json'
if (-not (Test-Path $pkg)) { Set-Content -Path $pkg -Value '{ "name": "cr-tools", "private": true, "version": "0.1.0" }' -Encoding ascii }
$dshInstalled = Test-Path (Join-Path $Root 'node_modules\@deepseek-ai\dsh\package.json')
if (-not $dshInstalled) {
  Say "installing DSH 0.1.1-rc.2 (local node_modules)..."
  Push-Location $Root
  try { & npm install --no-audit --no-fund @deepseek-ai/dsh@0.1.1-rc.2 }
  finally { Pop-Location }
  if ($LASTEXITCODE -ne 0) { throw "npm install DSH failed" }
} else { Say "DSH already installed (node_modules/@deepseek-ai/dsh)" }

# -- 3) pipeline venv + deps (tsinghua mirror for CN) --
$venvPy = Join-Path $Root 'pipeline\.venv\Scripts\python.exe'
if (-not (Test-Path $venvPy)) {
  Say "creating venv..."
  Push-Location (Join-Path $Root 'pipeline')
  try { & python -m venv .venv }
  finally { Pop-Location }
}
Say "installing pipeline deps (pip, tsinghua mirror)..."
Push-Location (Join-Path $Root 'pipeline')
try {
  & .\.venv\Scripts\python.exe -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
} finally { Pop-Location }
if ($LASTEXITCODE -ne 0) { throw "pip install failed" }

# -- 4) config.yaml from example --
$cfg = Join-Path $Root 'pipeline\config.yaml'
if (-not (Test-Path $cfg)) {
  Copy-Item (Join-Path $Root 'pipeline\config.yaml.example') $cfg
  Say "config.yaml created from example - edit it to fill your API keys"
} else { Say "config.yaml exists (keep as is)" }

# -- 5) DSH profile (project-local DSH_HOME, no user pollution) --
$profWeb = Join-Path $Root '.dsh-home\profiles\web'
New-Item -ItemType Directory -Path $profWeb -Force | Out-Null
Copy-Item (Join-Path $Root 'cordis.yml') (Join-Path $profWeb 'cordis.yml') -Force
# cordis.patch.yml: insert cr-plugin from local path
$patch = @"
# cr-tools source profile patch (generated by setup.ps1)
- insert:
    - id: cr-plugin
      name: 'cr-plugin'
      inject: ['fs', 'webServer', 'sandboxPolicy', 'workspaceRegistry']
"@
[System.IO.File]::WriteAllText((Join-Path $profWeb 'cordis.patch.yml'), $patch, [System.Text.Encoding]::UTF8)
$profCr = Join-Path $profWeb 'node_modules\cr-plugin'
New-Item -ItemType Directory -Path $profCr -Force | Out-Null
Copy-Item (Join-Path $Root 'cr-plugin\lib') (Join-Path $profCr 'lib') -Recurse -Force
Copy-Item (Join-Path $Root 'cr-plugin\package.json') (Join-Path $profCr 'package.json') -Force
Say "profile deployed: .dsh-home/profiles/web (DSH_HOME isolated)"

# -- 6) model hint --
Say "setup done."
Say "next: run 'powershell -ExecutionPolicy Bypass -File scripts\download-models.ps1' to fetch models (or follow docs\INSTALL.md), then start.bat."
